### ISSUE TITLE
Color Picker Choix par hexa/RGB/... pas toujours appliqué

### ISSUE THREAD

**Issue by KahlanCaulfield** [skarab42/marv#146]
![image](https://user-images.githubusercontent.com/58058000/107257150-aabb9680-6a3a-11eb-9d7e-629aedfbc9b9.png)
Lorsque qu'on rentre les valeurs de la couleur souhaité elle n'est pas "validé" et donc pas appliqué. Pour la valider il faut cliquer sur le dégrader au bon endroit.

Le bug ne se produit pas dans 100% des cas

**Comment by Arubinu** [comment]
J'ai répertorié un bug similaire mais pas toute à fait.
