### ISSUE TITLE
Deco reco en boucle du websocket avec mdp

### ISSUE THREAD

**Issue by ClementlaPizza** [skarab42/marv#167]
**Describe the bug**
Quand on met un mot de passe sur le websocket d'OBS (pour une raison de securiter pour ma part), Marv ce deco et reco en boucle (spam de notification pour dire deco et reco du websocket)

**Desktop:**
 - OS: W10 64 bits
 - Version [v1.6.0-HiDeoo](https://github.com/skarab42/marv/releases/tag/v1.6.0)

**OBS:**
 - Version 26.1.1
 - Websocket version : [4.9.0](https://github.com/Palakis/obs-websocket/releases/tag/4.9.0)

**Comment by WinXaito** [comment]
Pour résoudre ce problème, en attendant que la fonctionnalité soit implémenté dans Marv, il suffit de manuellement enregistrer le mot de passe de la connexion WebSocket dans la base de données de Marv. *(Vu avec skarab42 durant son live)*

- Utiliser un outil pour éditer la base de données (ex: `DB Browser for SQLite`)
- Ouvrir la base de données qui se trouve dans `C:\Users\xxx\AppData\Local\marv-nodejs\Data\database\marv.sqlite`
- Modifier le champs `obs.password` dans la table `Settings`
- Appliquer la modification et ne pas oublier d'enregistrer la base de données.

Marv devrais ensuite pouvoir se connecter sans problème.

**Comment by skarab42** [comment]
C'est possible a partir de la version >= 1.7.0
