### ISSUE TITLE
Installation plus possible

### ISSUE THREAD

**Issue by Keidennn** [skarab42/marv#18]
Bonjour ! 

Alors, j'ai télécharger Marv-Setup-0.15.0.exe sous windows 10, je l'ai installé puis quand j'ai tenter de le lier à mon compte twitch via le bouton, une fois le lien fait marv s'est juste éteint et supprimé. Et quand je tente de le réinstaller le .exe reste bloqué (cf le screen ci dessous)  et je ne peux plus rien en faire à part forcer via le gestionnaire des tâches pour eteindre

![image](https://user-images.githubusercontent.com/76847118/103443327-7811c780-4c5e-11eb-894f-c47d20aca394.png)
 Y'a également ça qui pop quand ça fait le soucis 
![image](https://user-images.githubusercontent.com/76847118/103443384-274e9e80-4c5f-11eb-8814-f3e8ec06d066.png)

**Comment by skarab42** [comment]
Hello
Essayer d'installer la dernière version
https://github.com/skarab42/marv/releases/tag/v0.16.0

Merci pour ton retour :)

**Comment by Keidennn** [comment]
Hello, 
J'ai testé en l'installant sans mon antivirus, donc j'sais pas si c'était l'antivirus ou la nouvelle version mais ça marche, merci !
