### ISSUE TITLE
Duplicate a button doesn't duplicate it's content

### ISSUE THREAD

**Issue by WinXaito** [skarab42/marv#181]
**Describe the bug**

When we duplicate a button, the internal settings is not duplicated. (eg. a text file)

**To Reproduce**
1. Create a button (action: Anime | Timeline)
2. Create a text file
3. Duplicate the button
4. Edit the text in duplicated button
5. The text is edited in the first button too

**Screenshots**
![image](https://user-images.githubusercontent.com/8223773/109419699-04c2d280-79cf-11eb-8a4a-2082b2c01ece.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - Version 1.6.0

**Comment by skarab42** [comment]
This is the expected behaviour. If you want to change the text you have to create another one and replace it with the new one.

**Comment by j-wiedemann** [comment]
https://clips.twitch.tv/SlickHealthyChipmunkDendiFace-oP9gAogYYXtQJD1N
