### ISSUE TITLE
UnhandledRejection Did not receive a reply to join #pacman_93320 in time; assuming that the join failed

### ISSUE THREAD

**Issue by pacman93** [skarab42/marv#191]
# Marv is redirecting you to this page because an error has occurred. Please complete the report below and send it to help developers resolve this issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: Windows_NT 6.1.7601 win32
- Marv: v1.6.0

**Browser**

- Version: [e.g. chrome, safari]

**Additional context**

**Stack trace**

```
UnhandledRejection: Error: Did not receive a reply to join #pacman_93320 in time; assuming that the join failed
    at Timeout._onTimeout (C:\Users\stephan\AppData\Local\Programs\marv\resources\app.asar\node_modules\twitch-chat-client\lib\ChatClient.js:2024:36)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by skarab42** [comment]
Fix by #207
