### ISSUE TITLE
OBS | Basculer source audio, "Aucune source sélectionnée" si OBS est lancé après Marv

### ISSUE THREAD

**Issue by Arubinu** [skarab42/marv#193]
**Describe the bug**
"Aucune source sélectionnée" apparait sur les bouton de type "OBS | Basculer source audio" si OBS Studio est lancé après Marv.

**To Reproduce**
1. Créer un bouton "OBS | Basculer source audio"
2. Sélectionner une source
3. Quitter Marv et OBS Studio
4. Lancer Marv, puis lancer ensuite OBS Studio
5. La source audio est toujours bien choisie dans le bouton mais le message ne s'enlève que quand on la change

**Expected behavior**
Que Marv rafraichisse le message au lancement d'OBS Studio, pour qu'il n'apparaisse pas quand la source est bien sélectionnée et présente dans OBS Studio.

**Screenshots**
![source_audio](https://user-images.githubusercontent.com/6209760/109629859-930c9500-7b44-11eb-9c3e-ca5bd13da576.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Marv
 - Version: https://github.com/skarab42/marv/tree/3808fdacbf8734b41ac2f6da233994a3112e5130

**Comment by skarab42** [comment]
Probablement fixé dans la PR #201
