### ISSUE TITLE
Marv ne réagit pas au /me

### ISSUE THREAD

**Issue by Arubinu** [skarab42/marv#197]
**Describe the bug**
Ce n'est pas vraiment un bug, mais j'ai essayé de faire une Animation lorsqu'un message commençant par "/me" arrive, mais rien.
J'ai donc essayé sans condition (sur l'évènement Message), mais aucune réaction de Marv.

**Expected behavior**
Serait-il possible de l'ajouter d'une manière ou d'une autre, pour faire une action spécifique au "/me" ?

**Desktop:**
 - OS: Windows 10
 - Browser: Marv
 - Version: https://github.com/skarab42/marv/tree/3808fdacbf8734b41ac2f6da233994a3112e5130

**Comment by skarab42** [comment]
Comme expliquer en live c'est l'évènement Action qui gère ça ;)
