### ISSUE TITLE
Port in use one time, could not get back to working state at all

### ISSUE THREAD

**Issue by cchampou** [skarab42/marv#2]
### Environment

**MacBook Pro** (13-inch, **2019**, Four Thunderbolt 3 ports)
**macOS** 10.15.7 (19H2)
**Firefox Developer Edition** 83.0b10
**NodeJS** 12.18.4
**yarn** 1.22.10

### Steps to reproduce

- `yarn install` => OK
- Built with `yarn build` => OK
- Launched with `yarn watch` **while another service was running on port 4242**
- Server started with port 4243.
- Stopped the server
- Stopped the service which was using port 4242
- Tried to relaunch with `yarn watch`
- Server started on port 4243 again

I this point, I tried figuring out how to revert to default port :
- Deleted data in `~/Library/Preferences/marv-nodejs`
- Deleted data in `~/Library/Application Support/marv-nodejs`
- Deleted whole project data
- Recloned and relaunched `yarn install`, `yarn build`, `yarn watch`
- Everything started correctly on port 4242

After visiting `http://localhost:4242/`, Firefox shows up in console :
```
Firefox ne peut établir de connexion avec le serveur à l’adresse ws://localhost:35729/livereload. livereload.js:2169:20
Firefox ne peut établir de connexion avec le serveur à l’adresse ws://localhost:4242/socket.io/?EIO=3&transport=websocket.
```
![Screenshot 2020-11-15 at 18 36 43](https://user-images.githubusercontent.com/23266335/99192145-86b92380-2771-11eb-8916-6e04f6636981.png)

**Comment by skarab42** [comment]
I think this is only true on dev mode, but still need a fix ! Thanks for reporting 👍

**Comment by skarab42** [comment]
Fixed in next release ;)
