### ISSUE TITLE
Chat spinner rouge constant

### ISSUE THREAD

**Issue by Arubinu** [skarab42/marv#220]
**Describe the bug**
L'avatar affiché dans Marv garde un serpentin rouge et `Chat` est bien en rouge avec l'icone qui tourne.
Malgré cet affichage, les commandes de tchat fonctionnent parfaitement.
Un redémarrage de Marv n'y change rien, mais j'avais constaté avec @skarab42 en live qu'un redémarrage du PC avait réglé le soucis (pas retenté depuis).

**To Reproduce**
1. Utiliser Marv normalement, et peut-être à force d'être relancé...

**Desktop:**
 - OS: Windows 10
 - Browser: Marv
 - Version: 53e4a27ae3bdfc1c9a417fa50662622ce5443851

**Comment by skarab42** [comment]
Ca devrais être fixé avec la version 1.8.0
