### ISSUE TITLE
[Mac] Error! Parameter redirect_uri does not match registered URI...

### ISSUE THREAD

**Issue by kadiks** [skarab42/marv#222]
**Describe the bug**

Lorsque je me connecte sur Twitch, j'ai l'erreur suivante :

`Error! Parameter redirect_uri does not match registered URI...`

**To Reproduce**
1. Clic sur `Connect with Twitch`
2. Clic sur `Continue` à la fenêtre qui affiche ce message  ![image](https://user-images.githubusercontent.com/526294/110491495-a219b700-80f1-11eb-914d-fc0d952f8fcf.png) avec cet [URL](https://id.twitch.tv/oauth2/authorize?response_type=token&client_id=d9szwgmmltndfb8mcg1t6mok5ghltn&redirect_uri=http%253A%252F%252Flocalhost%253A4242%252Ftwitch-auth&scope=user:read:email%20chat:read%20chat:edit%20channel:read:redemptions%20channel:manage:redemptions%20bits:read&force_verify=false) 
3. Puis j'arrive sur la page d'erreur avec ce [lien](http://localhost:4242/twitch-auth?error=redirect_mismatch&error_description=Parameter+redirect_uri+does+not+match+registered+URI)

**Desktop (please complete the following information):**
 - OS: Mac Catalina v10.15.3
 - Browser: Chrome et Safari

**Additional context**

Je sais pas si ça a un rapport, mais au démarrage de l'app, j'ai toujours cette erreur :

![image](https://user-images.githubusercontent.com/526294/110492022-181e1e00-80f2-11eb-9787-1d04ccf8177c.png)

**Comment by HiDeoo** [comment]
The first error should be fixed by https://github.com/skarab42/marv/pull/214. Same goes for the second one and https://github.com/skarab42/marv/pull/212.

The PRs have been merged but not yet released so both errors should be fixed in the next Marv version.

**Comment by kadiks** [comment]
@HiDeoo Indeed, building from the source works!

Closing it. Thanks for the PR!
