### ISSUE TITLE
UnhandledRejection invalid json response body at https://api.twitch.tv/helix/users/follows?to_id=66246555&first=100 reason: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by syrm** [skarab42/marv#258]
# Marv is redirecting you to this page because an error has occurred. Please complete the report below and send it to help developers resolve this issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: Windows_NT 10.0.19043 win32
- Marv: v1.7.0

**Browser**

- Version: [e.g. chrome, safari]

**Additional context**

**Stack trace**

```
UnhandledRejection: FetchError: invalid json response body at https://api.twitch.tv/helix/users/follows?to_id=66246555&first=100 reason: Unexpected token < in JSON at position 0
    at C:\Users\srm\AppData\Local\Programs\marv\resources\app.asar\node_modules\node-fetch\lib\index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by skarab42** [comment]
closed by #261
