### ISSUE TITLE
UnhandledRejection invalid json response body at https://api.twitch.tv/helix/users/follows?to_id=492156857&first=100 reason: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Jonathan67110** [skarab42/marv#260]
# Marv is redirecting you to this page because an error has occurred. Please complete the report below and send it to help developers resolve this issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: Linux 5.4.0-66-generic linux
- Marv: v1.7.0

**Browser**

- Version: [e.g. chrome, safari]

**Additional context**

**Stack trace**

```
UnhandledRejection: FetchError: invalid json response body at https://api.twitch.tv/helix/users/follows?to_id=492156857&first=100 reason: Unexpected token < in JSON at position 0
    at /tmp/.mount_Marv-1OCy5im/resources/app.asar/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by skarab42** [comment]
closed by #261
