### ISSUE TITLE
[Feature] UI / Déplacer le bouton "Mode édition"

### ISSUE THREAD

**Issue by b00um** [skarab42/marv#30]
Hello,

Petite proposition qui à mon sens améliorerait la lisibilité.
Actuellement, le bouton "Mode édition" à côté des panneaux prend pas mal de place (je trouve).

Serait-il possible d'activer le mode édition en passant par le burger menu par exemple ?

![image](https://user-images.githubusercontent.com/38693862/103486981-fe1a4380-4e01-11eb-9d1e-98c9d652b70f.png)

**Comment by skarab42** [comment]
C'est vrais que c'est pratique pour moi quand je dev, car j'édit les panneaux constamment. Mais pour un user lambda c'est pas génial. Le menu burger est une possibilité. Mais je pense aussi a un longpress sur la topbar.
