### ISSUE TITLE
[Feature] UI / Pouvoir modifier l'ordre des panneaux

### ISSUE THREAD

**Issue by b00um** [skarab42/marv#31]
Hello,

Proposition d'ajout d'une feature sur les panneaux.
Une fois qu'ils sont créés on ne peut plus les déplacer -> µIl faut donc prendre soin de les créer dans l'ordre qui conviendra le mieux à leur utilisation.

Proposition : lorsqu'on est en mode édition, pouvoir les déplacer via un drag & drop ?

![image](https://user-images.githubusercontent.com/38693862/103487026-77199b00-4e02-11eb-9a03-ad19f46af61b.png)

**Comment by skarab42** [comment]
Yep c'est prévus dans une v1.x ;)

**Comment by skarab42** [comment]
Ajouter dans la prochaine version ;)
