### ISSUE TITLE
[MacOS] Marv se lance mais ne s'affiche pas

### ISSUE THREAD

**Issue by bt0r** [skarab42/marv#5]
# Description
Après avoir télécharger le dernier build `0.8.2` j'ai tenté de le lancer sur macos, Marv se lance bien dans la barre des tâches par contre la fenetre n'est pas visible, j'ai découvert qu'il y avait un process sur `localhost:4242` en lancant un build sous linux en CLI `./Marv-0.8.2.AppImage`, la fenètre ne s'est pas lancé mais a affiché un message `Running on http://localhost:4242`

### Infos
**Marv**: 0.8.2
**MacOS**: 10.15.7 (Catalina)

### Apercu 
https://streamable.com/88kd8v

Si tu as besoins de faire des tests sur MacOS ou de plus d'infos, hésite pas à me ping 👋🏻

**Comment by bt0r** [comment]
### News !
J'ai compris pourquoi ! 
* Electron se lance bien mais ne se met pas en premier plan, Marv est bien dans la barre des tâches ET la barre des icones
* Le logo de marv n'est pas redimensionné, ce qui fait qu'au premier regard je pensais à un bug graphique (voir apercu)

Du coup il faudrait juste faire en sorte que la fenetre s'affiche directement et que le logo soit bien dimensionné dans la barre des icones

### Apercu
https://streamable.com/427oei

**Comment by skarab42** [comment]
Merci c'est merged 👍
