### ISSUE TITLE
Mode edition non fonctionnel

### ISSUE THREAD

**Issue by ClementlaPizza** [skarab42/marv#54]
Quand je veux creer un overlay, je passe en mode edition mais cela reste vide.
Je ne peux rien faire

OS : W10
Version : v1.0.0-Iti63
Maj depuis : v0.16.0-TerminabloxHD

![image](https://user-images.githubusercontent.com/21962065/103906908-8af92180-50ce-11eb-93a5-80f09a702671.png)

**Comment by skarab42** [comment]
Hello merci pour le report ! 
Ca devrais être fixer avec la version https://github.com/skarab42/marv/releases/tag/v1.0.1 
Merci de me tenir au courant.
