### ISSUE TITLE
[Bug] Prefix de commande reste actif

### ISSUE THREAD

**Issue by ClementlaPizza** [skarab42/marv#64]
J'ai supprimer directement le panneau auquel j'avais mis une commande pour la tester.
Mais la fonction avec le prefix reste actif (voir image)

Version Marv : v1.0.1-Iti63-fix
OS : Win 10
Logiciel de stream : OBS Studio 26.1.0

![image](https://user-images.githubusercontent.com/21962065/104196980-7381a780-53f2-11eb-9749-b88f38e7e5a1.png)

**Comment by skarab42** [comment]
C'est normale, supprimer le panneau de commande ne supprime pas les commandes et heureusement ;) Tu dois supprimer les commandes dans le panneau! Rajoute le a nouveau et ta commande devrais toujours y être, ensuite supprime la et voilà ;)

**Comment by ClementlaPizza** [comment]
ok
