### ISSUE TITLE
Pas de prise en compte de la durée de la timeline des champs texte

### ISSUE THREAD

**Issue by BurukunTV** [skarab42/marv#65]
version testée : 1.0.1-iti63

**Scénario de reproduction :**

- Créer une anime timeline avec une vidéo et objet texte
- Dans la timeline, faire démarrer le texte après le lancement de la vidéo et le faire se terminer avant la fin de la vidéo

Ci-dessous un exemple avec 1 vidéo, 1 audio et 2 champs textes :
![image](https://user-images.githubusercontent.com/77299115/104232385-92168b80-5450-11eb-9ec1-b439e0ec7666.png)

**Résultat attendu :**
A la lecture de l'animation, les champs textes apparaissent uniquement selon la durée et la position prévue dans la timeline

**Résultat obtenu :**
A la lecture de l'animation, les champs textes apparaissent tout le long de la vidéo

**Comment by skarab42** [comment]
C'est le comportement attendus. 
C'est a toi de cacher/montrer le texte quand tu le souhaite avec des clés d'animations.
Je te montre en live si besoins.
