### ISSUE TITLE
On boarding pas clair

### ISSUE THREAD

**Issue by Akanoa** [skarab42/marv#9]
Au tout démarrage de l'application, le premier écran n'est pas forcément très clair.

![image](https://user-images.githubusercontent.com/4521637/100548042-5641b100-326a-11eb-8d48-1cd27e0d579a.png)

L'ajout d'un panneau se fait en appuyant sur le bouton "engrenage" puis "+" puis le bouton pour rajouter les panneaux.

Il faudrait au minimum que le bouton "+" pour ajouter des pouvoir soit visible dès le début. L'engrenage ne donne pas envie de cliquer dessus ^^

Peut-être améliorer l'onboarding de l'application pour le premier lancement :)

**Comment by skarab42** [comment]
Ca été amélioré dans la v0.10.0 ;)
